print(type(5))
print(type(5.5))
print(type('5.5'))
print(type(True))
print(type("True"))
print('------------------')
#Functionalities in PRINT STATEMENT
print('a')
print('b')
print('c')
print('a','b','c',sep=" $ ")
print('a',end=" ")
print('b',end=" ")
print('c',end=" ")